name: Nix
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    # Run once per day
    - cron: '0 0 * * *'
env:
  CI_REGISTRY: ghcr.io
  CI_PROJECT_PATH: ${{ github.repository }}
jobs:
  build:
    strategy:
      # Keep building the other channels if one fails
      fail-fast: false
      matrix:
        channel:
          - nixos-unstable
          - nixos-23.05
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CI_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: nix-shell --run ./ci.sh
        env:
          NIXPKGS_CHANNEL: '${{ matrix.channel }}'
